package figurasgeometricas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thom1
 */
public class winFig extends javax.swing.JFrame {

    /**
     * Creates new form winFig
     */
    public winFig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SinglePDialog = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        DualPDialog = new javax.swing.JDialog();
        ErrorDialog = new javax.swing.JDialog();
        errorLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Options = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        perimetro = new javax.swing.JButton();
        area = new javax.swing.JButton();
        TipoTriangulo = new javax.swing.JButton();
        perimetroLbl = new javax.swing.JLabel();
        areaLbl = new javax.swing.JLabel();
        tipoTLabel = new javax.swing.JLabel();
        param1 = new javax.swing.JTextField();
        param2 = new javax.swing.JTextField();
        param2.setVisible(false);
        paramLbl = new javax.swing.JLabel();
        hipotenusa = new javax.swing.JButton();
        hipotenusa.setEnabled(false);
        hipotenusaLbl = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout SinglePDialogLayout = new javax.swing.GroupLayout(SinglePDialog.getContentPane());
        SinglePDialog.getContentPane().setLayout(SinglePDialogLayout);
        SinglePDialogLayout.setHorizontalGroup(
            SinglePDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SinglePDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SinglePDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SinglePDialogLayout.setVerticalGroup(
            SinglePDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SinglePDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DualPDialogLayout = new javax.swing.GroupLayout(DualPDialog.getContentPane());
        DualPDialog.getContentPane().setLayout(DualPDialogLayout);
        DualPDialogLayout.setHorizontalGroup(
            DualPDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DualPDialogLayout.setVerticalGroup(
            DualPDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        ErrorDialog.setMinimumSize(new java.awt.Dimension(490, 110));

        errorLbl.setText("jLabel3");

        jButton1.setText("Ok");

        javax.swing.GroupLayout ErrorDialogLayout = new javax.swing.GroupLayout(ErrorDialog.getContentPane());
        ErrorDialog.getContentPane().setLayout(ErrorDialogLayout);
        ErrorDialogLayout.setHorizontalGroup(
            ErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ErrorDialogLayout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(199, 199, 199))
        );
        ErrorDialogLayout.setVerticalGroup(
            ErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Circulo", "Rectangulo", "Cuadrado", "Triangulo Rectangulo" }));
        Options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido a la UI de la actividad 3 parte 2.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione una figura en el menu a continuacion:");

        perimetro.setText("Calcular Perimetro");
        perimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perimetroActionPerformed(evt);
            }
        });

        area.setText("Calcular Area");
        area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaActionPerformed(evt);
            }
        });

        TipoTriangulo.setText("Tipo de triangulo");
        TipoTriangulo.setEnabled(false);
        TipoTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoTrianguloActionPerformed(evt);
            }
        });

        perimetroLbl.setText("Perimetro del circulo");

        areaLbl.setText("Area de el Circulo");

        tipoTLabel.setBackground(new java.awt.Color(255, 153, 153));
        tipoTLabel.setText("Solo valido para triangulos.");

        param1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param1ActionPerformed(evt);
            }
        });
        param1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                param1KeyPressed(evt);
            }
        });

        param2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param2ActionPerformed(evt);
            }
        });
        param2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                param2KeyPressed(evt);
            }
        });

        paramLbl.setText("Inserte el radio de su Circulo:");

        hipotenusa.setText("Calcular Hipotenusa");
        hipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hipotenusaActionPerformed(evt);
            }
        });

        hipotenusaLbl.setText("Solo valido para triangulos.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Options, javax.swing.GroupLayout.Alignment.LEADING, 0, 370, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(perimetro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(area, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TipoTriangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(hipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(perimetroLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(areaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipoTLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hipotenusaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paramLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramLbl)
                    .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perimetro)
                    .addComponent(perimetroLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(area)
                    .addComponent(areaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoTriangulo)
                    .addComponent(tipoTLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hipotenusa)
                    .addComponent(hipotenusaLbl))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perimetroActionPerformed
        String sele= (String)Options.getSelectedItem();
        int p1;
        int p2;
        try{
            p1= Integer.parseInt(param1.getText());
            if (sele =="Circulo"){
                Circulo c= new Circulo(p1);
                perimetroLbl.setText(Double.toString(c.calcularPerimetro()));
                
            }else if(sele== "Rectangulo"){
                p2= Integer.parseInt(param2.getText());
                Rectangulo c= new Rectangulo(p1, p2);
                perimetroLbl.setText(Double.toString(c.calcularPerimetro()));
    
            }else if(sele=="Cuadrado"){
                Cuadrado c= new Cuadrado(p1);
                perimetroLbl.setText(Double.toString(c.calcularPerimetro()));
 
            }else if(sele=="Triangulo Rectangulo"){
                p2= Integer.parseInt(param2.getText());
                TrianguloRectangulo c= new TrianguloRectangulo(p1, p2);
                perimetroLbl.setText(Double.toString(c.calcularPerimetro()));
            }
        }catch(Exception err){
            errorLbl.setText(err.toString());
            ErrorDialog.show(true);
        }
    }//GEN-LAST:event_perimetroActionPerformed

    private void areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaActionPerformed
        String sele= (String)Options.getSelectedItem();
        int p1;
        int p2;
        try{
            p1= Integer.parseInt(param1.getText());
            if (sele =="Circulo"){
                Circulo c= new Circulo(p1);
                areaLbl.setText(Double.toString(c.calcularArea()));
                
            }else if(sele== "Rectangulo"){
                p2= Integer.parseInt(param2.getText());
                Rectangulo c= new Rectangulo(p1, p2);
                areaLbl.setText(Double.toString(c.calcularArea()));
    
            }else if(sele=="Cuadrado"){
                Cuadrado c= new Cuadrado(p1);
                areaLbl.setText(Double.toString(c.calcularArea()));
 
            }else if(sele=="Triangulo Rectangulo"){
                p2= Integer.parseInt(param2.getText());
                TrianguloRectangulo c= new TrianguloRectangulo(p1, p2);
                areaLbl.setText(Double.toString(c.calcularArea()));
            }
        }catch(Exception err){
            errorLbl.setText(err.toString());
            ErrorDialog.show(true);
        }
    }//GEN-LAST:event_areaActionPerformed

    private void TipoTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoTrianguloActionPerformed
        int p1;
        int p2;
        try{
            p1= Integer.parseInt(param1.getText());
            p2= Integer.parseInt(param2.getText());
            TrianguloRectangulo c= new TrianguloRectangulo(p1, p2);
            tipoTLabel.setText(c.determinarTipoTriangulo());            
        }catch(Exception err){
            ErrorDialog.show(true);
        }
    }//GEN-LAST:event_TipoTrianguloActionPerformed

    private void OptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionsActionPerformed
        String sele= (String)Options.getSelectedItem();
        try{
            param1.setText("");
            param2.setText("");
            if (sele =="Circulo"){
                param2.setVisible(false);
                perimetroLbl.setText("Perimetro del Circulo");
                areaLbl.setText("Area del Circulo");
                paramLbl.setText("Inserte el radio del Circulo:");
                
            }else if(sele== "Rectangulo"){
                perimetroLbl.setText("Perimetro del Rectangulo");
                areaLbl.setText("Area del Rectangulo");
                paramLbl.setText("Inserte base y altura:");
                param2.setVisible(true);
                
            }else if(sele=="Cuadrado"){
                param2.setVisible(false);
                perimetroLbl.setText("Perimetro del Cuadrado");
                areaLbl.setText("Area del Cuadrado");
                paramLbl.setText("Inserte el lado del Cuadrado:");
                
            }else if(sele=="Triangulo Rectangulo"){
                perimetroLbl.setText("Perimetro del Triangulo");
                areaLbl.setText("Area del Triangulo");
                tipoTLabel.setText("Tipo de Triangulo");
                hipotenusaLbl.setText("Hipotenusa del triangulo");
                paramLbl.setText("Inserte base y altura:");
                param2.setVisible(true);
                TipoTriangulo.setEnabled(true);
                hipotenusa.setEnabled(true);
            }
            
        }catch(Exception error){
            errorLbl.setText(error.toString());
            ErrorDialog.show(true);
        }
    }//GEN-LAST:event_OptionsActionPerformed

    private void param1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_param1ActionPerformed

    private void param2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_param2ActionPerformed

    private void hipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hipotenusaActionPerformed
        int p1;
        int p2;
        try{
            p1= Integer.parseInt(param1.getText());
            p2= Integer.parseInt(param2.getText());
            TrianguloRectangulo c= new TrianguloRectangulo(p1, p2);
            hipotenusaLbl.setText(Double.toString(c.calcularHipotenusa()));            
        }catch(Exception err){
            errorLbl.setText(err.toString());
            ErrorDialog.show(true);
        }
    }//GEN-LAST:event_hipotenusaActionPerformed

    private void param1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_param1KeyPressed
        perimetroLbl.setText("");
        areaLbl.setText("");
        if(param2.isVisible()){
            tipoTLabel.setText("");
            hipotenusaLbl.setText("");
        }
    }//GEN-LAST:event_param1KeyPressed

    private void param2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_param2KeyPressed
        perimetroLbl.setText("");
        areaLbl.setText("");
        tipoTLabel.setText("");
        hipotenusaLbl.setText("");
    }//GEN-LAST:event_param2KeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(winFig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(winFig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(winFig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(winFig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new winFig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DualPDialog;
    private javax.swing.JDialog ErrorDialog;
    private javax.swing.JComboBox<String> Options;
    private javax.swing.JDialog SinglePDialog;
    private javax.swing.JButton TipoTriangulo;
    private javax.swing.JButton area;
    private javax.swing.JLabel areaLbl;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JButton hipotenusa;
    private javax.swing.JLabel hipotenusaLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField param1;
    private javax.swing.JTextField param2;
    private javax.swing.JLabel paramLbl;
    private javax.swing.JButton perimetro;
    private javax.swing.JLabel perimetroLbl;
    private javax.swing.JLabel tipoTLabel;
    // End of variables declaration//GEN-END:variables

}
